<?php 
 	return array (
  'institute_name' => 'Xerone IT',
  'institute_address' => 'Holding No. 127, 1st Floor, Gonok Para',
  'institute_email' => 'admin@gmail.com',
  'institute_mobile' => '01521418384',
  'time_zone' => 'Europe/Dublin',
  'slogan' => '#1 The Most Complete Visitor Analytics & SEO Tools',
  'language' => 'en',
  'product_name' => 'SiteSpy',
  'product_short_name' => 'SiteSpy',
  'master_password' => '*****',
  'email_sending_option' => 'smtp',
  'force_https' => '1',
  'enable_support' => '1',
  'enable_signup_form' => '1',
  'delete_junk_data_after_how_many_days' => '31',
  'mailchimp_list_id' => '',
  'xeroseo_file_upload_limit' => '4',
  'use_admin_app' => 'yes',
  'logo' => "data:image/png;base64,".base64_encode(file_get_contents(base_path('assets/img/logo.png'))),
  'favicon' => "data:image/png;base64,".base64_encode(file_get_contents(base_path('assets/img/favicon.png'))),
);
